services:
  - type: web
    name: hirehelp-backend
    env: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: hirehelp
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: BLOCKCHAIN_NETWORK
        value: sepolia
      - key: SMART_CONTRACT_ADDRESS
        sync: false
      - key: BLOCKCHAIN_RPC_URL
        sync: false
      - key: BLOCKCHAIN_WALLET_ADDRESS
        sync: false
      - key: BLOCKCHAIN_PRIVATE_KEY
        sync: false
      - key: ENABLE_Z3_VALIDATION
        value: "True"
